# Generated by Django 5.1.7 on 2025-05-14 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession/Fonction')),
                ('profile_photo', models.ImageField(blank=True, help_text='Formats acceptés: JPG, PNG, MP4 (max 4MB)', null=True, upload_to='temoignages/medias/profiles/', verbose_name='Photo Profil')),
                ('note', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (sur 5)')),
                ('contenu', models.TextField(verbose_name='Témoignage')),
                ('media', models.FileField(blank=True, help_text='Formats acceptés: JPG, PNG, MP4 (max 5MB)', null=True, upload_to='temoignages/medias/', verbose_name='Média (photo/vidéo)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé et publié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de modération')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('consentement_publication', models.BooleanField(default=False, verbose_name='Consentement à la publication')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_publication', '-date_soumission'],
                'constraints': [models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='note_entre_1_et_5')],
            },
        ),
    ]
