# Generated by Django 5.2 on 2025-05-15 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('sujet', models.CharField(choices=[('support', 'Support technique'), ('devis', 'Demande de devis'), ('partenariat', 'Partenariat'), ('autre', 'Autre demande')], max_length=20)),
                ('message', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nom complet de votre entreprise', max_length=100, verbose_name="Nom de l'entreprise")),
                ('contact_person', models.CharField(max_length=100, verbose_name='Personne de contact')),
                ('company_email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email professionnel')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('partnership_type', models.CharField(choices=[('technology', 'Partenaire Technologique'), ('reseller', 'Partenaire Revendeur'), ('strategic', 'Partenaire Stratégique'), ('other', 'Autre')], max_length=20, verbose_name='Type de partenariat')),
                ('collaboration_ideas', models.TextField(verbose_name='Idées de collaboration')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Demande traitée')),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-submission_date'],
            },
        ),
    ]
