# Generated by Django 5.1.7 on 2025-05-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0002_contactmessage_partnershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='collaboration_ideas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='company_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='partnership_type',
            field=models.CharField(choices=[('technology', 'Partenaire Technologique'), ('reseller', 'Partenaire Revendeur'), ('strategic', 'Partenaire Stratégique'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
